MedicalPractice.WebUI/Models/CartIndexViewModel.cs
using MedicalPractice.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MedicalPractice.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

MedicalPractice.WebUI/Models/OrderData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MedicalPractice.WebUI.Models
{
    public class OrderData
    {
    }
}

MedicalPractice.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalPractice.Domain.Abstract;
using MedicalPractice.Domain.Entities;
using MedicalPractice.WebUI.Models;
using SportsStore.Domain.Abstract;

namespace MedicalPractice.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IMedicalProductsRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IMedicalProductsRepository repo, IOrderProcessor order)
        {
            repository = repo;
            orderProcessor = order;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Medical_Products product = repository.ProductsRepository.FirstOrDefault(p => p.Medical_ProductsID == productId);
            
            if(product != null)
            {
                cart.AddItem(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {                       
            cart.RemoveItem(productId);
            
            return RedirectToAction("Index", new { returnUrl });
        }

        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        // GET: Cart
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View("CartIndex", new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new VisitDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, VisitDetails shippingDetails)
        {
            if (cart.List.Count() == 0)
            {
                ModelState.AddModelError("", "Koszyk jest pusty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }

            else
            {
                return View(shippingDetails);
            }
        }
    }
}

MedicalPractice.WebUI/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalPractice.Domain.Abstract;
using MedicalPractice.Domain.Entities;

namespace SportsStore.WebUI.Controllers
{
    public class DoctorsController : Controller
    {
        private IDoctorsRepository repository;
        public DoctorsController(IDoctorsRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List()
        {
            return View("List2", repository.DorcorRepository);
        }
    }
}

MedicalPractice.WebUI/Controllers/MedicalProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalPractice.Domain.Abstract;

namespace MedicalPractice.WebUI.Controllers
{
    public class MedicalProductsController : Controller
    {
        private IMedicalProductsRepository repository;
        public MedicalProductsController(IMedicalProductsRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult Index()
        {
            return View("Products", repository.ProductsRepository);
        }
    }
}

MedicalPractice.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalPractice.WebUI.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        public ActionResult Menu()
        {
            return PartialView();
        }
    }
}

MedicalPractice.WebUI/Controllers/VisitOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalPractice.Domain.Entities;

namespace MedicalPractice.WebUI.Controllers
{
    public class VisitOrderController : Controller
    {

        public RedirectToRouteResult Order(string d, string returnUrl)
        {            
            return RedirectToAction("Index", d);
        }

        public ViewResult Index(string name, string surname, int id, string returnUrl)
        {
            return View(new Model1 { Name = name, Surname  = surname, Id = id});
        }
    }

    public class Model1
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Id { get; set; }
    }
}

MedicalPractice.WebUI/Views/Cart/CartIndex.cshtml
@model MedicalPractice.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "CartIndex";
}
<style>
    table {
        align-content: center;
        table-layout: fixed;
        width: 70% !important;
    }
    tfoot {
        background-color: palegreen;
    }
    
</style>

<h2>CartIndex</h2>

<table class="table text-center">
    <thead>
        <tr>
            <th>Produkt</th>
            <th class="text-right">Cena</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.List)
        {
            <tr>
                <td class="text-left">@line.Name</td>
                <td class="text-right">@line.Price.ToString("c")</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        <div class="buttonCenter">
                            @Html.Hidden("productId", line.Medical_ProductsID)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input type="submit" class="btn btn-success" value="Usuń" />
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="1" class="text-left">Razem:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Kontynuuj zakupy</a>
    @Html.ActionLink("Złóż zamówienie", "Checkout", null, new { @class = "btn btn-primary" })
</div>

MedicalPractice.WebUI/Views/Cart/Checkout.cshtml
@model MedicalPractice.Domain.Entities.VisitDetails

@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        <div class="form-group">
            <label>@(property.DisplayName ?? property.PropertyName)</label>
            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
        </div>
    }

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Zakończ zamówienie" />
    </div>
}

MedicalPractice.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Sklep portowy: zamówienie zostało przesłane";
}
<h2>Dziękujemy!</h2>
Dziękujemy za złożenie zamówienia. Wyślemy produkty tak szybko, jak tylko będzie to możliwe.

MedicalPractice.WebUI/Views/Doctors/List.cshtml
@using MedicalPractice.Domain.Entities;
@model IEnumerable<Doctor>

@{
    ViewBag.Title = "Lekarze";
}

<style>
    h2 {
        text-align: center;        
    }

    .button-right {
        margin-left: 900px;        
    }

</style>

<h2>Nasi Lekarze</h2>
<h2></h2>
@foreach (var l in Model)
{
    @Html.Partial("DoctorSummary", l);
}

MedicalPractice.WebUI/Views/Doctors/List2.cshtml
@using MedicalPractice.Domain.Entities;
@model IEnumerable<Doctor>

@{
    ViewBag.Title = "List2";
}

<h2>List2</h2>

<style>
    h2 {
        text-align: center;
    }

    .button-right {
        margin-left: 900px;
    }
</style>

<h2>Nasi Lekarze</h2>

@foreach (var l in Model)
{
    @Html.Partial("DoctorSummary", l);
}

MedicalPractice.WebUI/Views/MedicalProducts/Products.cshtml
@model IEnumerable<MedicalPractice.Domain.Entities.Medical_Products>

@*@{
    ViewBag.Title = "Products";
}*@

<h2>Products</h2>

@foreach (var m in Model)
{
    @Html.Partial("ProductSummary", m);
}

MedicalPractice.WebUI/Views/Nav/Menu.cshtml
<style>
    .cart {
        background-color: green;
        color: white !important;
    }
    .cart:hover {
        background-color: lightgreen;
        color: white !important;
    }
    
</style>


<div class="container-fluid">
    
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Nasi lekarze", "List", "Doctors", null, new { @class = "active" })</li>
        <li>@Html.ActionLink("Pakiety", "Index", "MedicalProducts", null, new { @class = "active" })</li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Pakiety", "Index", "MedicalProducts", null, new { @class = "cart active" })</li>
    </ul>
</div>

MedicalPractice.WebUI/Views/Shared/DoctorSummary.cshtml
@model MedicalPractice.Domain.Entities.Doctor
@using MedicalPractice.WebUI.Controllers;

<style>
    input {
        position: absolute;
        top: 10px;
        left: 90%;
    }
</style>

<div class="list-group-item">
    <p> @Model.Name @Model.Surname  @Model.Specjalization</p>
    @using (Html.BeginForm("Index", "VisitOrder"))
    {
        <div class="pull-right">
            @Html.Hidden("Name", Model.Name )
            @Html.Hidden("Surname", Model.Surname)
            @Html.Hidden("id", Model.DoctorID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Umów wizytę" />
        </div>
    }
</div>

MedicalPractice.WebUI/Views/Shared/ProductSummary.cshtml
@model MedicalPractice.Domain.Entities.Medical_Products

@{
    ViewBag.Title = "ProductSummary";
}
   
<style>
    .product {
        width: 250px;
        height: 290px;
        border: 2px solid red;
        border-radius: 15%;
        display: inline-block;
        margin: 10px 5px;
    }
    .name {
        font-size: 20px;
        font-weight: bold;
    }
    .desc {
        text-align:justify;
        padding: 0 15px;
    }
    .buttonCenter {
        text-align: center;
    }
</style>

<div class="product">
    <p class="text-center name">@Model.Name</p>
    <p class="text-center desc">@Model.Description</p>
    <p class="text-center">@Model.Price zł</p>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="buttonCenter">
            @Html.Hidden("productId", Model.Medical_ProductsID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Dodaj do koszyka" />
        </div>
    }
    
</div>

MedicalPractice.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    #wrapper {
        max-width: 1000px;
        margin: 0 auto;
        background-color: white;
    }
</style>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        img {
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="wrapper">        
        <div class="container">
            <img src="~/dr_with_stethoscope-optimized.jpg" />
            <nav class="navbar navbar-default">
                @Html.Action("Menu", "Nav")
            </nav>
            @*<nav id="categories" class="col-xs-3">                
                
            </nav>*@
            <div class="list-group">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

MedicalPractice.WebUI/Views/VisitOrder/Index.cshtml
@model MedicalPractice.WebUI.Controllers.Model1

@{
    ViewBag.Title = "Order";
}
<style>
    .input-width {
        width: 500px;
        display: inline-block
    }
    span {
        display: inline-block;
        border: 1px solid red;
        background-color: darkred;
        color: white;
        border-radius: 5px;
        margin: 10px;
        padding: 5px;
    }
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
<script>
    $(function () {
        $("#txtDate").datepicker();
    });
</script>

<body>
    <h2>Order</h2>
    <form class="col-xs-4">
        <div class="form-group">
            <label for="email">Lekarz:</label>
            <label>   @Model.Name  @Model.Surname</label>
        </div>
        <div id="input" class="form-group">
            <label for="email">Email address:</label>
            <input type="email" class="form-control" id="email">
            <span id="email-message"></span>
        </div>

        <div>
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
    
    <form id="form1" runat="server">
        <div>
            <asp:TextBox ID="txtDate" runat="server" ReadOnly="true"></asp:TextBox>
            <asp:Button ID="Button1" runat="server" Text="Button" OnClick="Button1_Click" />
        </div>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
        function isEmail(email) {
            var regex = /^([a-zA-Z0-9_.+-])+\@@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            return regex.test(email);
        }
        $("#email-message").hide();
        $("#email").on("blur", function (event) {
            if (isEmail($(this).val())) {
                $("#input").removeClass("has-error");
                $("#email-message").hide();
            } else {                
                $("#email-message").text("zły adres email");
                $("#email-message").show();
                $("#input").addClass("has-error");
            }
        })
        $("#email").on("focus", function (event) {
            $("#input").removeClass("has-error");
        })
    </script>

</body>